# Generated by Django 6.0.5 on 2026-05-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_available_product_slug_product_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
